#!/usr/bin/env python3
"""
QueryBridge — Deterministic Demo Seed Script

Creates the certified demo environment from a clean database:
  - 3 sales datasets (North, South, ERP) with exact revenue totals
  - 5 knowledge base documents for RAG certification
  - Semantic mappings auto-generated by the dynamic engine

DESIGN PRINCIPLES:
  - Deterministic: same CSVs → same revenue every time
  - Idempotent: safe to run repeatedly without double-counting
  - Workspace-aware: seeds into the "default" workspace
  - Verifiable: prints exact values for certification

USAGE:
  python scripts/seed_demo.py               # seed if workspace empty
  python scripts/seed_demo.py --force       # clear + re-seed
  python scripts/seed_demo.py --verify-only # just verify, don't seed

REPRODUCIBILITY:
  After `docker compose down -v && docker compose up -d`, run:
    docker compose exec api python scripts/seed_demo.py
  This restores the complete demo environment.
"""

import argparse
import hashlib
import os
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

# Ensure project root is on sys.path
_project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from src import config


# ═══════════════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════════════

TEST_DATASETS_DIR = os.path.join(_project_root, "tests", "test_datasets")

DEMO_DATASETS = [
    {
        "filename": "sales_region_north.csv",
        "label": "Dataset A (North)",
        "target_revenue": 366979.88,
    },
    {
        "filename": "sales_region_south.csv",
        "label": "Dataset B (South)",
        "target_revenue": 328460.90,
    },
    {
        "filename": "sales_export_erp.csv",
        "label": "Dataset C (ERP)",
        "target_revenue": 255697.35,
    },
]

COMBINED_TARGET = 951138.13
DELETE_TARGET = 584158.25  # Combined - North

DEFAULT_WORKSPACE = "default"

# Knowledge base documents to seed
KB_DOCS = [
    "trade_promotion_policy.md",
    "sustainability_and_compliance.md",
    "pricing_and_margin_policy.md",
    "quality_and_recall_policy.md",
    "category_management_strategy.md",
]


# ═══════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════

def d(val):
    """Quantize to 2 decimal places."""
    return float(Decimal(str(val)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def _get_connection():
    """Get a fresh PostgreSQL connection."""
    import psycopg2
    if not config.USE_POSTGRESQL or not config.DATABASE_URL:
        raise RuntimeError("PostgreSQL required for seeding")
    return psycopg2.connect(config.DATABASE_URL)


def workspace_has_data(workspace_id: str = DEFAULT_WORKSPACE) -> bool:
    """Check if workspace already has structured data assets."""
    try:
        conn = _get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM assets "
                "WHERE workspace_id = %s AND status = 'ready' AND type = 'structured'",
                (workspace_id,),
            )
            count = cur.fetchone()[0]
            return count > 0
        finally:
            conn.close()
    except Exception:
        return False


def workspace_asset_count(workspace_id: str = DEFAULT_WORKSPACE) -> int:
    """Count structured assets in workspace."""
    try:
        conn = _get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM assets "
                "WHERE workspace_id = %s AND status = 'ready' AND type = 'structured'",
                (workspace_id,),
            )
            return cur.fetchone()[0]
        finally:
            conn.close()
    except Exception:
        return 0


def kb_has_documents() -> bool:
    """Check if knowledge base documents are indexed."""
    kb_dir = Path(config.KB_DIR)
    if not kb_dir.exists():
        return False
    for doc in KB_DOCS:
        if not (kb_dir / doc).exists():
            return False
    return True


def get_total_revenue(workspace_id: str = DEFAULT_WORKSPACE) -> float:
    """Get current total revenue from workspace data."""
    from src.analytics.dynamic_engine import workspace_total_revenue
    result = workspace_total_revenue(workspace_id)
    return result if result is not None else 0.0


# ═══════════════════════════════════════════════════════════════════════
# SEEDING
# ═══════════════════════════════════════════════════════════════════════

def clear_workspace(workspace_id: str = DEFAULT_WORKSPACE):
    """Delete all assets from the workspace (for --force re-seed)."""
    from src.analytics.dynamic_engine import list_datasets, delete_dataset

    print("[seed] Clearing workspace...")
    datasets = list_datasets(workspace_id)
    for ds in datasets:
        did = ds.get("dataset_id")
        if did:
            try:
                delete_dataset(did)
                print(f"  Deleted dataset: {did}")
            except Exception as e:
                print(f"  Warning: failed to delete {did}: {e}")

    # Clear knowledge base documents from DB
    try:
        conn = _get_connection()
        try:
            cur = conn.cursor()
            cur.execute("DELETE FROM embeddings WHERE chunk_id IN (SELECT chunk_id FROM document_chunks)")
            cur.execute("DELETE FROM document_chunks")
            cur.execute("DELETE FROM documents")
            cur.execute("DELETE FROM assets WHERE type = 'unstructured'")
            conn.commit()
            print("  Cleared knowledge base records")
        finally:
            conn.close()
    except Exception as e:
        print(f"  Warning: failed to clear KB records: {e}")

    # Do NOT delete knowledge base .md files from KB_DIR — they are
    # committed in the Docker image and are the source of truth.
    # Only delete the vector store cache.

    # Clear vector store
    vs_path = Path(config.VECTOR_STORE_PATH)
    if vs_path.exists():
        vs_path.unlink()
        print("  Deleted vector store")

    print("[seed] Workspace cleared.")


def seed_datasets(workspace_id: str = DEFAULT_WORKSPACE) -> dict:
    """Upload the 3 demo datasets. Returns {filename: revenue}."""
    from src.analytics.dynamic_engine import ingest_file

    print("\n[seed] Seeding demo datasets...")
    results = {}

    for ds in DEMO_DATASETS:
        filepath = os.path.join(TEST_DATASETS_DIR, ds["filename"])
        if not os.path.exists(filepath):
            print(f"  ERROR: {filepath} not found. Run: python tests/generate_test_datasets.py")
            continue

        with open(filepath, "rb") as f:
            file_bytes = f.read()

        label = ds["label"]
        print(f"  Uploading {label} ({ds['filename']})...")

        try:
            result = ingest_file(file_bytes, ds["filename"], workspace_id)
            total_rows = result.get("total_rows", 0)
            print(f"    → {total_rows} rows ingested")
        except Exception as e:
            print(f"    ERROR: {e}")
            continue

    # Verify revenue after all uploads
    print("\n[seed] Verifying revenue ground truths...")
    total = get_total_revenue(workspace_id)
    print(f"  Combined revenue: {total:.2f} (target: {COMBINED_TARGET:.2f})")
    if abs(total - COMBINED_TARGET) < 1.0:
        print("  ✅ Revenue matches target")
    else:
        print(f"  ❌ Revenue mismatch: {total:.2f} != {COMBINED_TARGET:.2f}")

    # Get per-dataset revenue by region/source
    from src.analytics.dynamic_engine import workspace_revenue_by_dimension
    by_region = workspace_revenue_by_dimension("region", workspace_id)
    for r in by_region:
        print(f"  {r['dimension']}: {r['revenue']:.2f}")

    by_source = workspace_revenue_by_dimension("source", workspace_id)
    if by_source:
        for r in by_source:
            print(f"  Source {r['dimension']}: {r['revenue']:.2f}")

    return {"total_revenue": total, "by_region": by_region}


def seed_knowledge_docs():
    """Write knowledge base markdown files and reindex."""
    print("\n[seed] Seeding knowledge base documents...")
    kb_dir = Path(config.KB_DIR)
    kb_dir.mkdir(parents=True, exist_ok=True)

    docs_written = 0
    for doc_name in KB_DOCS:
        dest = kb_dir / doc_name
        if dest.exists():
            print(f"  {doc_name} already exists, skipping")
            continue

        # Source is the committed doc in data/knowledge_base/
        source = Path(_project_root) / "data" / "knowledge_base" / doc_name
        if source.exists():
            import shutil
            shutil.copy2(str(source), str(dest))
            print(f"  Copied {doc_name}")
            docs_written += 1
        else:
            print(f"  WARNING: source {source} not found")

    # Always reindex if vector store is missing or empty.
    # After --force clear, the .md files still exist on disk (Docker COPY)
    # but the vector store pickle was deleted.
    needs_reindex = False
    vs_path = Path(config.VECTOR_STORE_PATH)
    if not vs_path.exists():
        needs_reindex = True
        print("  Vector store missing — will reindex")

    if docs_written > 0 or needs_reindex:
        print(f"\n[seed] Reindexing pipeline...")
        try:
            from src.rag.pipeline import get_pipeline
            pipeline = get_pipeline()
            if len(pipeline.vector_store.chunks) == 0:
                pipeline.reindex()
                print(f"  ✅ Pipeline reindexed: {len(pipeline.vector_store.chunks)} chunks")
            else:
                print(f"  Pipeline already indexed: {len(pipeline.vector_store.chunks)} chunks")
        except Exception as e:
            print(f"  ❌ Reindex failed: {e}")
    else:
        print("  All documents already present and indexed")

    # Verify document count
    try:
        from src.rag.pipeline import get_pipeline
        pipeline = get_pipeline()
        doc_ids = set()
        for c in pipeline.vector_store.chunks:
            doc_ids.add(c.document_id)
        print(f"\n[seed] Knowledge base: {len(doc_ids)} documents, {len(pipeline.vector_store.chunks)} chunks")
    except Exception as e:
        print(f"  Warning: could not verify docs: {e}")


def verify_certification_values():
    """Run all certification value checks."""
    print("\n" + "=" * 60)
    print("CERTIFICATION VALUE VERIFICATION")
    print("=" * 60)

    all_pass = True

    # Revenue verification
    total = get_total_revenue()
    checks = [
        ("Combined Revenue", total, COMBINED_TARGET),
    ]

    for name, actual, expected in checks:
        passed = abs(actual - expected) < 1.0
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"  {status}: {name} = {actual:.2f} (expected {expected:.2f})")
        if not passed:
            all_pass = False

    # Region breakdown
    from src.analytics.dynamic_engine import workspace_revenue_by_dimension
    by_region = workspace_revenue_by_dimension("region")
    region_targets = {"North": 366979.88, "South": 328460.90, "West": 255697.35}
    for r in by_region:
        region = r["dimension"]
        rev = r["revenue"]
        if region in region_targets:
            target = region_targets[region]
            passed = abs(rev - target) < 1.0
            status = "✅ PASS" if passed else "❌ FAIL"
            print(f"  {status}: {region} Revenue = {rev:.2f} (expected {target:.2f})")
            if not passed:
                all_pass = False

    # Delete verification: North removed = 584158.25
    # (We verify this is achievable, not the current state)
    remaining = d(COMBINED_TARGET - region_targets.get("North", 0))
    passed = abs(remaining - DELETE_TARGET) < 0.01
    status = "✅ PASS" if passed else "❌ FAIL"
    print(f"  {status}: Combined - North = {remaining:.2f} (expected {DELETE_TARGET:.2f})")
    if not passed:
        all_pass = False

    # Knowledge base verification
    try:
        from src.rag.pipeline import get_pipeline
        pipeline = get_pipeline()
        doc_ids = set()
        for c in pipeline.vector_store.chunks:
            doc_ids.add(c.document_id)
        passed = len(doc_ids) >= 3
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"  {status}: Knowledge docs = {len(doc_ids)} (expected ≥3)")
        if not passed:
            all_pass = False
    except Exception as e:
        print(f"  ❌ FAIL: Knowledge base check error: {e}")
        all_pass = False

    # Semantic mapping verification
    try:
        from src.analytics.dynamic_engine import discover_available_data
        data = discover_available_data()
        has_revenue = "revenue" in data["available_measures"]
        has_discount = "discount" in data["available_measures"]
        passed = has_revenue and has_discount
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"  {status}: Semantic mappings (revenue={has_revenue}, discount={has_discount})")
        if not passed:
            all_pass = False
    except Exception as e:
        print(f"  ❌ FAIL: Semantic mapping check error: {e}")
        all_pass = False

    print("\n" + "=" * 60)
    if all_pass:
        print("STATUS: ALL CHECKS PASSED")
    else:
        print("STATUS: SOME CHECKS FAILED — investigate before certification")
    print("=" * 60)

    return all_pass


# ═══════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="QueryBridge Demo Seed Script")
    parser.add_argument("--force", action="store_true", help="Clear workspace and re-seed")
    parser.add_argument("--verify-only", action="store_true", help="Only verify, don't seed")
    parser.add_argument("--skip-kb", action="store_true", help="Skip knowledge base seeding")
    args = parser.parse_args()

    print("=" * 60)
    print("QUERYBRIDGE DEMO SEED SCRIPT")
    print(f"Database: {'PostgreSQL' if config.USE_POSTGRESQL else 'NOT CONFIGURED'}")
    print(f"Workspace: {DEFAULT_WORKSPACE}")
    print("=" * 60)

    if not config.USE_POSTGRESQL:
        print("\n❌ ERROR: PostgreSQL is required. Set DATABASE_URL environment variable.")
        sys.exit(1)

    if args.verify_only:
        success = verify_certification_values()
        sys.exit(0 if success else 1)

    if args.force:
        clear_workspace()

    # Check if workspace already has data
    has_data = workspace_has_data()
    if has_data and not args.force:
        print("\n[seed] Workspace already has data. Use --force to re-seed.")
        print(f"[seed] Current asset count: {workspace_asset_count()}")
        # Still verify
        verify_certification_values()
        return

    # Seed datasets
    seed_datasets()

    # Seed knowledge docs
    if not args.skip_kb:
        seed_knowledge_docs()

    # Final verification
    verify_certification_values()

    print("\n[seed] Demo environment seeding complete.")
    print(f"[seed] Total assets: {workspace_asset_count()}")


if __name__ == "__main__":
    main()
